# Generated by Django 4.2.24 on 2025-12-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
