# Generated by Django 4.2.24 on 2025-12-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_canvas_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='network',
            field=models.CharField(default='', max_length=255),
        ),
    ]
